- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    # Change repositories to Yandex mirrors
    - include_tasks: tasks/repositories.yml
    # Install packages
    - include_tasks: tasks/snapd.yml # Enables installation of snap on Linux Mint
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/thonny.yml # Thonny needs to be...edited a little bit. Removes the flag.
    # Make users, including ansible user for automatic pulling
    - include_tasks: tasks/users.yml
    # Set cron jobs
    - include_tasks: tasks/cron.yml
