- hosts: localhost
  connection: local
  become: true
  vars:
    domain: ad.rischool.ru
    dc_ip: 192.168.88.252  # IP address of domain controller

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    # Change repositories to Yandex mirrors
    #- include_tasks: tasks/repositories.yml
    # Configure snap installer
    - include_tasks: tasks/snapd.yml
    # Install packages
    - include_tasks: tasks/packages.yml
    # Edit packages
    - include_tasks: tasks/thonny.yml # Thonny needs to be...edited a little bit. Removes the flag.
    # Make users, including ansible user for automatic pulling
    - include_tasks: tasks/users.yml
    # Set cron jobs
    - include_tasks: tasks/cron.yml
    # Join domain
    - include_tasks: tasks/domain_join.yml
    # Enable automatic creation of home directories for Debian-based systems.
    # This is automatically enabled in RedHat-based systems.
    - include_tasks: tasks/mkhomedir.yml
      when: ansible_os_family == 'Debian'
    # Turn on manual login, so users can type in their domain usernames.
    - include_tasks: tasks/manual_login.yml
    # Set the user's home directory on the file server to mount at ~/MySharedFolders
    - include_tasks: tasks/mount.yml
    # Configure the automatic setup of home profile for new users
    - include_tasks: tasks/home_profile.yml
    # Install Veyon and import its configuration. Prevent pupils from launching Veyon Master.
    - include_tasks: tasks/veyon.yml
    # Configure new pofiles with /etc/skel
     - include_tasks: tasks/skel.yml
