- name: install cronie # MOS doesn't have it for some reason
  package:
    name: cronie
  when: ansible_facts['distribution'] == 'MOS'

- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/passmore-ris/ansible_pull_config.git > /dev/null"
