- name: Install cronie # MOS doesn't have it for some reason
  ansible.builtin.package:
    name: cronie
  when: ansible_facts['distribution'] == 'MOS'

- name: Install cron job (ansible-pull)
  ansible.builtin.cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/passmore-ris/ansible_pull_config.git > /dev/null"
