# Ubuntu systems need to have the universe and multiverse repositories enabled. Linux Mint systems should have them enabled by default.
- name: Get current hostname
  command: hostname
  register: current_hostname
  changed_when: false

- name: Set new hostname with domain
  hostname:
    name: "{{ current_hostname.stdout }}.{{ domain }}"

- name: Modify resolved info
  lineinfile:
    path: /etc/systemd/resolved.conf
    search_string: '#DNS='
    line: DNS={{ dc_ip }}
    owner: root
    group: root
    mode: '0644'

- name: Restart resolved
  service:
    name: systemd-resolved
    state: restarted

- name: Install dependencies
  apt:
    name:
      - realmd
      - libnss-sss
      - libpam-sss
      - sssd
      - sssd-tools
      - adcli
      - samba-common-bin
      - oddjob
      - oddjob-mkhomedir
      - packagekit
  when: ansible_facts['distribution'] in ['Ubuntu', 'Linux Mint']

#- name: install expect using pip
#  pip:
#    name: pexpect

- name: Join host to domain
  expect:
    # The variables domain_admin_username and domain_admin_password
    # must be specified in the --extra-vars argument in the original
    # ansible-pull command.
    command: sudo realm join -U "{{ domain_admin_username }}" "{{ domain }}"
    responses: 
      (?i)password*: "{{ domain_admin_password }}"
  no_log: true   # Don't want passwords shown in logs

# Enable automatic creation of  home directories for each user.
# This is automatically enabled in the RedHat family.
- import_playbook: mkhomedir.yml
  when: ansible_os_family == "Debian"

- name: Allow all users to log in
  command: sudo realm permit --all

- name: Grant domain admins sudo access
  copy:
    src: files/sudoers_domain_admins
    dest: /etc/sudoers.d/domain_admins
    owner: root
    group: root
    mode: 0440

# Turn on manual login, so users can type in the domain usernames.
- import_playbook: manual_login.yml
