- name: Copy firefox policies to /etc/firefox/policies/policies.json
  ansible.builtin.copy:
    src: files/firefox_policies.json
    dest: /usr/lib/firefox-esr/distribution/policies.json
    owner: root
    group: root
    mode: '0644'
