- name: Create policies.json file
  ansible.builtin.file:
    path: /etc/firefox/policies/policies.json

- name: Copy firefox policies to /etc/firefox/policies/policies.json
  ansible.builtin.copy:
    src: files/firefox_policies.json
    dest: /etc/firefox/policies/policies.json
    owner: root
    group: root
    mode: '0440'
