- name: Check if GNOME is in use
  ansible.builtin.stat:
    path: /usr/bin/gnome-shell
  register: gnome_shell

- name: Turn on manual login for Linux Mint workstations
  ansible.builtin.copy:
    src: files/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['distribution'] == 'Linux Mint'

- name: Turn on manual login for MOS workstations
  ansible.builtin.copy:
    src: files/uid.conf
    dest: /etc/sddm.conf.d/uid.conf
    owner: root
    group: root
    mode: '0664'
  when: ansible_facts['distribution'] == 'MOS'

#- name: Turn on manual login for Debian workstations
#  ansible.builtin.lineinfile:
#    path: /etc/gdm3/greeter.dconf-defaults
#    regexp: '^#?disable-user-list=false'
#    line: 'disable-user-list=true'
#  when: ansible_facts['distribution'] == 'Debian'

- name: Configure login screen for GNOME workstations
  when: gnome_shell.stat.exists
  block:
    - name: Create /etc/dconf/profile/gdm file
      ansible.builtin.file:
        path: /etc/dconf/profile/gdm
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Ensure logo directory exists
      ansible.builtin.file:
        path: /usr/share/pixmaps/logo
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: Copy logo to workstation
      ansible.builtin.copy:
        src: files/ris-logo.png
        dest: /usr/share/pixmaps/logo/ris-logo.png
        owner: root
        group: root
        mode: '0644'

    - name: Add content to /etc/dconf/profile/gdm
      ansible.builtin.blockinfile:
        path: /etc/dconf/profile/gdm
        block: |
          user-db:user
          system-db:gdm
          file-db:/usr/share/gdm/greeter-dconf-defaults

    - name: Create login screen database directory
      ansible.builtin.file:
        path: /etc/dconf/db/gdm.d
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: Create login screen configuration
      ansible.builtin.file:
        path: /etc/dconf/db/gdm.d/00-login-screen
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Add content to /etc/dconf/db/gdm.d/00-login-screen
      ansible.builtin.blockinfile:
        path: /etc/dconf/db/gdm.d/00-login-screen
        block: |
          [org/gnome/login-screen]
          disable-user-list=true
          logo='/usr/share/pixmaps/logo/ris-logo.png'

    - name: Update dconf database
      ansible.builtin.command: dconf update
      changed_when: false
