- name: Edit pam-configs/mkhomedir file
  ansible.builtin.copy:
    src: files/pam_mkhomedir
    dest: /usr/share/pam-configs/mkhomedir
    owner: root
    group: root
    mode: '0644'

- name: Enable the mkhomedir profile using pam-auth-update
  ansible.builtin.command: sudo pam-auth-update --enable mkhomedir

# - name: Restart sssd
#   ansible.builtin.service:
#     name: sssd
#     state: restarted
#   when: "'sssd' in ansible_facts.packages"
