- name: Install apt packages
  package:
    name:
      - openshot-qt
      - htop
      - snapd
      - inkscape
      - geany
      - thonny # Workbench.py must be changed. See 'thonny.yml'
      - gimp
      - audacity
      - dia
      - tmux
      - fd

- name: Install packages with snap
  snap:
    name:
      - turbowarp-desktop
      - blender
      - pinta
      - sqlitebrowser
      - sublime-text
    classic: true
    state: present

- name: Install .deb files
  apt:
    deb: https://archive.ubuntu.com/ubuntu/pool/universe/a/anki/anki_2.1.15+dfsg-3ubuntu4_all.deb
  ignore_errors: yes
