########################
# Prepare dependencies #
########################
- name: Install depedencies for debian-based systems
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
      - ca-certificates
      - flatpak
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

# Add repositories

- name: Add deb repositories
  when: ansible_os_family == 'Debian'
  block:
    - name: Download OnlyOffice GPG key from Ubuntu keyserver
      ansible.builtin.get_url:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xCB2DE8E5"
        dest: /usr/share/keyrings/onlyoffice.asc
        owner: root
        group: root
        mode: '0644'

    - name: Add OnlyOffice DEB822 repository
      ansible.builtin.deb822_repository:
        name: onlyoffice
        types: deb
        uris: https://download.onlyoffice.com/repo/debian
        suites: squeeze
        components: main
        signed_by: /usr/share/keyrings/onlyoffice.asc

    - name: Add Sublime repository
      ansible.builtin.deb822_repository:
        name: sublime
        types: deb
        uris: https://download.sublimetext.com
        suites: apt/stable/
        signed_by: https://download.sublimetext.com/sublimehq-pub.gpg

    - name: Add Google Chrome deb repository
      ansible.builtin.deb822_repository:
        name: google-chrome
        types: deb
        uris: https://dl.google.com/linux/chrome-stable/deb/
        suites: stable
        components: main
        architectures: amd64
        signed_by: https://dl.google.com/linux/linux_signing_key.pub

- name: Ensure the Flathub repository is enabled
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: system # Use 'user' if you don't have sudo access
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

##############################################
# Install packages common to pupils and staff#
##############################################

- name: Install apt packages for both pupil and staff workstations
  ansible.builtin.apt:
    name:
      - sublime-text
      - vlc
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install flatpaks for both pupil and staff workstations
  community.general.flatpak:
    name: org.onlyoffice.desktopeditors
    remote: flathub
    state: present
    method: system

###########################################
# Install packages for pupil workstations #
###########################################

- name: Install packages for pupil workstations
  when: ansible_local.workstation.role.name | default('pupil') == 'pupil'
  block:
    - name: Install apt packages for pupil workstations
      ansible.builtin.package:
        name:
          - blender
          - inkscape
          - geany
          - thonny # Workbench.py must be changed. See 'thonny.yml'
          - gimp
          - audacity
          - dia
          - sqlitebrowser
          - tmux
          - libreoffice-l10n-ru # Russian language pack for LibreOffice
        update_cache: true

# Special method for installing Turbowarp Desktop on Debian-based systems

    - name: Check for Turbowarp installation file
      ansible.builtin.stat:
        path: /opt/turbowarp-desktop.deb
      register: turbowarp_installer

    - name: Download Turbowarp Desktop installer
      when: not turbowarp_installer.stat.exists
      block:
        - name: Download deb package for Turbowarp Desktop
          ansible.builtin.get_url:
            url: https://github.com/TurboWarp/desktop/releases/download/v1.16.0/TurboWarp-linux-amd64-1.16.0.deb
            dest: /opt/turbowarp-desktop.deb
            mode: '0644'
        - name: Install Turbowarp Desktop
          ansible.builtin.apt:
            deb: /opt/turbowarp-desktop.deb
            state: present

###########################################
# Install packages for staff workstations #
###########################################

- name: Install packages for staff workstations
  when: ansible_local.workstation.role.name | default('pupil') == 'staff'
  block:
    - name: Add Google Chrome yum repository
      ansible.builtin.yum_repository:
        name: google-chrome
        description: Google Chrome Repository
        baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
        gpgcheck: true
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        enabled: true
      when: ansible_os_family == 'RedHat'

    - name: Install general packages for staff workstations
      ansible.builtin.package:
        name:
          - google-chrome-stable
        update_cache: true

    - name: Install apt-specific packages for staff workstations
      ansible.builtin.apt:
        name:
          - libreoffice-l10n-ru # Russian language pack for LibreOffice
          - errands
          - okular
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install flatpaks for staff workstations
      community.general.flatpak:
        name:
          - md.obsidian.Obsidian
        remote: flathub
        state: present
        method: system

#    - name: Install dnf-specific packages
#      ansible.builtin.dnf:
#        name:
#          -
#        state: present
#      when: ansible_os_family == 'RedHat'
