# Debian repositories
- name: Set Debian repositories to Yandex mirrors
  ansible.builtin.copy:
    src: files/apt_repositories/debian
    dest: /etc/apt/sources.list
    mode: '0440'
  when: ansible_facts['distribution'] == 'Debian'

- name: Update cache
  ansible.builtin.package:
    update_cache: true
