- name: Make backup of file preventing installation of snapd
  ansible.builtin.copy:
    remote_src: true
    src: /etc/apt/preferences.d/nosnap.pref
    dest: /etc/apt/preferences.d/nosnap.backup
  ignore_errors: true

- name: Remove file preventing installation of snapd
  ansible.builtin.file:
    path: /etc/apt/preferences.d/nosnap.pref
    state: absent
  ignore_errors: true
