- name: Check if Veyon has already been downloaded
  ansible.builtin.stat:
    path: "{{ veyon_download_path }}"
  register: veyon_downloaded

- name: Download Veyon
  when: not veyon_downloaded.stat.exists
  block:
    - name: Download Veyon .deb for Ubuntu
      ansible.builtin.get_url:
        url: https://github.com/veyon/veyon/releases/download/v4.10.1/veyon_4.10.1.0-ubuntu.24.04_amd64.deb # Ubuntu 24.04
        dest: "{{ veyon_download_path }}"
        owner: root
        group: root
        mode: '0644'
      when:
       - ansible_facts['distribution'] in ['Ubuntu', 'Linux Mint']
       - ansible_facts['distribution_major_version'] == '24.04'

    - name: Download Veyon .deb for Debian 13
      ansible.builtin.get_url:
        url: https://github.com/veyon/veyon/releases/download/v4.10.4/veyon_4.10.4.0-debian.13_amd64.deb
        dest: "{{ veyon_download_path }}"
        owner: root
        group: root
        mode: '0644'
      when:
        - ansible_facts['distribution'] == 'Debian'
        - ansible_facts['distribution_major_version'] == '13'

    - name: Download Veyon .rpm for Rocky/Alma/CentOS/RedHat 10
      ansible.builtin.get_url:
        url: https://github.com/veyon/veyon/releases/download/v4.10.4/veyon-4.10.4.0-rhel.10.x86_64.rpm
        dest: "{{ veyon_download_path }}"
        owner: root
        group: root
        mode: '0644'
      when:
        - ansible_os_family == 'RedHat'
        - ansible_facts['distribution_major_version'] == '10' 

- name: Install Veyon .deb package
  ansible.builtin.apt:
    deb: "{{ veyon_download_path }}"
  when: ansible_os_family == 'Debian'

# - name: Install Veyon Master
#   ansible.builtin.apt:
#     name: veyon-master
#     state: present

- name: Install Veyon .rpm package
  ansible.builtin.dnf:
    name: "{{ veyon_download_path }}"
  when: ansible_os_family == 'RedHat'

- name: Transfer Veyon configuration
  ansible.builtin.copy:
    src: files/freeipa_veyon_config.json
    dest: /etc/veyon_config.json
    owner: root
    group: root
    mode: '0640'

- name: Import Veyon configuration
  ansible.builtin.command: sudo veyon-cli config import /etc/veyon_config.json
  changed_when: false

# # Need to make it so that only domain admins and teachers can access it.
# - name: Prevent pupils from executing Veyon-Master
#   ansible.posix.acl:
#     path: /usr/bin/veyon-master
#     entity: pupils
#     etype: group
#     permissions: r--
#     state: present
#   when: ansible_facts['distribution'] != 'MOS' # MOS uses an old version of ansible that doesn't work with this module.

- name: Only allow staff to execute Veyon Master
  ansible.builtin.file:
    path: /usr/bin/veyon-master
    owner: root
    group: '10000'
    mode: '0755'
