- name: Check if XFCE is installed
  ansible.builtin.stat:
    path: /usr/bin/xfce4-session
  register: xfce_check

- name: Disable Pride wallpaper in GNOME settings
  community.general.xml:
    path: /usr/share/gnome-background-properties/pride.xml
    xpath: /wallpapers/wallpaper
    attribute: deleted
    value: "true"

- name: Add cosmic wallpapers
  ansible.builtin.unarchive:
    src: files/cosmic_wallpapers.tar.gz
    dest: /usr/share/backgrounds/gnome/
    owner: root
    group: root
    mode: '0644'

- name: Update xml for cosmic wallpapers
  ansible.builtin.copy:
    src: files/extra_wallpapers.xml
    dest: /usr/share/gnome-background-properties/extra_wallpapers.xml
    owner: root
    group: root
    mode: '0644'

- name: Add school logo to icons
  ansible.builtin.copy:
    src: files/ris_logo.png
    dest: /usr/share/icons/ris_logo.png
    owner: root
    group: root
    mode: '0644'
  when: xfce_check.stat.exists
