- name: Remove rainbow wallpapers
  ansible.builtin.file:
    path: /usr/share/backgrounds/gnome/pride-d.jxl
    state: absent

- name: Remove rainbow wallpapers
  ansible.builtin.file:
    path: /usr/share/backgrounds/gnome/pride-l.jxl
    state: absent

- name: Add cosmic wallpapers
  ansible.builtin.unarchive:
    src: files/cosmic_wallpapers.tar.gz
    dest: /usr/share/backgrounds/gnome/
    owner: root
    group: root
    mode: '0644'
