// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1769105796);
user_pref("app.update.lastUpdateTime.background-update-timer", 1769105796);
user_pref("app.update.lastUpdateTime.region-update-timer", 1769105796);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1769105796);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1769105796);
user_pref("browser.region.update.updated", 1769105766);
user_pref("browser.search.region", "DE");
user_pref("calendar.caldav.googleResync", 1769105765);
user_pref("calendar.list.sortOrder", "ef386c53-b68c-4402-99aa-c117056e4be8");
user_pref("calendar.registry.ef386c53-b68c-4402-99aa-c117056e4be8.calendar-main-default", true);
user_pref("calendar.registry.ef386c53-b68c-4402-99aa-c117056e4be8.calendar-main-in-composite", true);
user_pref("calendar.registry.ef386c53-b68c-4402-99aa-c117056e4be8.disabled", true);
user_pref("calendar.registry.ef386c53-b68c-4402-99aa-c117056e4be8.name", "Home");
user_pref("calendar.registry.ef386c53-b68c-4402-99aa-c117056e4be8.type", "storage");
user_pref("calendar.registry.ef386c53-b68c-4402-99aa-c117056e4be8.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Moscow");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "c3bf3b8d-e793-484e-be4d-41fce80ba038");
user_pref("datareporting.dau.cachedUsageProfileID", "c3861a8c-12ed-4077-aef5-eb86e24b8613");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1769105774769");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.cache.lastUpdate", 1769105796);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.hasExperimentsInstalled", false);
user_pref("extensions.hasExtensionsInstalled", false);
user_pref("extensions.installedDistroAddon.langpack-en-CA@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-GB@thunderbird.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-US@thunderbird.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20260109054016");
user_pref("extensions.lastAppVersion", "140.7.0");
user_pref("extensions.lastPlatformVersion", "140.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"75525307-b033-4b24-85f3-f2e25dde24e9\"}");
user_pref("mail.rights.version", 1);
user_pref("mail.ui-rdf.version", 51);
user_pref("mailnews.database.global.datastore.id", "c99b6d94-8786-40f9-afd5-de586167cee");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.start_page_override.mstone", "140.7.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("services.settings.clock_skew_seconds", -7341);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1769113137);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1769113137);
user_pref("services.settings.thunderbird.search-config.last_check", 1769113137);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1769113137);
user_pref("toolkit.startup.last_success", 1769105762);
user_pref("toolkit.telemetry.cachedClientID", "4a25e976-2939-4318-8eaa-f8d0a17086b7");
user_pref("toolkit.telemetry.cachedProfileGroupID", "5a6b0cf9-99af-459b-a756-69d97f375577");
user_pref("toolkit.telemetry.previousBuildID", "20260109054016");
